### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by asim** [micro/web#12]
- [ ] Strip endpoint list from service cards on main page
- [ ] Make service cards on main page clickable
- [ ] Move per service view to display endpoints in left hand menu with form for calls in main view
- [ ] Renamed "Definition" to "API" in per service page
- [ ] Rename "Call" to "JSON" and add separate "Form" view,
- [ ] Add Script or JS tab for calls with sample code
- [ ] Replace raw json call black color scheme with white or grey background
- [ ] Replace purple buttons with same aqua colour as on website
- [ ] Remove + button from login page
- [ ] Change register button on login page to link under submit "[Sign up]() if you don't  have an account"
- [ ] Change circular plus button to github style + dropdown with "New Service" in the menu
- [ ] Add the rest of status info for a service into Process tab e.g owner, group, last updated, etc
- [ ] Change "Process" to Info aka Status Info
- [ ] Remove stats and nodes tabs
- [ ] Add Info page tab for services so it includes name, version, metadata
